# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Pa\xeds'},
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default=1, max_length=45, verbose_name='Nombre del Pais'),
            preserve_default=False,
        ),
    ]
