# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='idPais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apirest.Pais', verbose_name='Pa\xeds'),
            preserve_default=False,
        ),
    ]
